[project]
name = "eip-format"
authors = ["EIP Developer"]
description = "A Clarity smart contract suite for standardized token formatting and management"
telemetry = false
requirements = []
[contracts.token-format]
path = "contracts/token-format.clar"
depends_on = []

[contracts.token-registry]
path = "contracts/token-registry.clar"
depends_on = []

[contracts.token-validator]
path = "contracts/token-validator.clar"
depends_on = []

[contracts.token-admin]
path = "contracts/token-admin.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
